# Generated by Django 5.0.6 on 2026-05-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clave",
                    models.CharField(
                        choices=[("civil", "Civil"), ("familiar", "Familiar")],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ["clave"],
            },
        ),
        migrations.CreateModel(
            name="Organo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("clave", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("distrito", models.CharField(max_length=100)),
                (
                    "materia",
                    models.CharField(
                        choices=[("civil", "Civil"), ("familiar", "Familiar")],
                        max_length=20,
                    ),
                ),
                ("direccion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Órganos",
                "ordering": ["clave"],
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("slug", models.SlugField(max_length=40, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "portal",
                    models.CharField(
                        choices=[
                            ("ciudadano", "Ciudadano"),
                            ("interno", "Interno"),
                            ("admin", "Admin"),
                            ("interinst", "Interinstitucional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Roles",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="TipoJuicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("clave", models.CharField(max_length=30, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "materia",
                    models.CharField(
                        choices=[("civil", "Civil"), ("familiar", "Familiar")],
                        max_length=20,
                    ),
                ),
                ("es_especializado", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Tipos de juicio",
                "ordering": ["materia", "nombre"],
            },
        ),
    ]
